version: 2

artifacts:
  - name: main
    build:
      type: tier4/iv/main/amd64/v2

simulations:
  - name: lexus_planning_sim
    type: planning_sim_v2
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: simulator/standard1/amd64/medium
        cpu: 8
        memory: 16384
      parameters:
        launch_autoware: "true"
        autoware_launch_package: autoware_launch
        autoware_launch_file: planning_simulator.launch.xml
        architecture_type: awf/universe
        vehicle_model: solio
        sensor_model: aip_xx1
        initialize_duration: "45"
  - name: localization
    type: localization
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: simulator/standard1/amd64/medium
        cpu: 8
        memory: 16384

release:
  components:
    - name: planning
      deployment:
        type: container
        artifact: main
    - name: perception
      deployment:
        type: container
        artifact: main
