version: 2

artifacts:
  - name: main
    build:
      type: tier4/universe/main/amd64/v1

simulations:
  - name: planning_sim_v2
    type: planning_sim_v2
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: simulator/standard1/amd64/medium
        cpu: 8
        memory: 16384
      parameters:
        vehicle_model: solio
        sensor_model: aip_xx1
        use_foa: "true"
        use_external_lc: "false"
        autoware_launch_package: autoware_launch
        autoware_launch_file: planning_simulator.launch.xml
        architecture_type: awf/universe
        initialize_duration: "90"

  - name: log_sim_v2
    type: log_sim_v2
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: simulator/standard1/amd64/medium
        cpu: 8
        memory: 16384

  - name: perception
    type: perception
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: gpu1/amd64/large
      pre_tasks:
        - exec: source /home/autoware/autoware.proj/install/setup.bash && ros2 run ml_model_provider convert_onnx_to_trt_engine.sh --package-name lidar_centerpoint --model-name aip_xx1 --model-path $(ros2 pkg prefix ml_model_provider --share)/data/lidar_centerpoint
          mounts:
            - volume: model
      volumes:
        - name: model
          path: /home/autoware/autoware.proj/install/ml_model_provider/share/ml_model_provider/data/lidar_centerpoint
          preserve_original_files: true

release:
  components:
    - name: autoware
      deployment:
        type: rootfs
        artifact: main
