---
- name: TensorRT (install libraries for TensorRT 8)
  become: yes
  apt:
    name:
      - libcudnn8={{ cudnn_version }}
      - libcudnn8-dev={{ cudnn_version }}
      - libnvinfer8={{ tensorrt_version }}
      - libnvinfer-dev={{ tensorrt_version }}
      - libnvinfer-plugin8={{ tensorrt_version }}
      - libnvinfer-plugin-dev={{ tensorrt_version }}
      - libnvonnxparsers8={{ tensorrt_version }}
      - libnvonnxparsers-dev={{ tensorrt_version }}
      - libnvparsers8={{ tensorrt_version }}
      - libnvparsers-dev={{ tensorrt_version }}
    update_cache: yes

- name: TensorRT (prevent cuda related packages from upgrading)
  become: yes
  command: apt-mark hold "{{ item }}"
  with_items:
    - cuda-11-4
    - libcudnn8
    - libcudnn8-dev
    - libnvinfer8
    - libnvinfer-dev
    - libnvinfer-plugin8
    - libnvinfer-plugin-dev
    - libnvonnxparsers8
    - libnvonnxparsers-dev
    - libnvparsers8
    - libnvparsers-dev
