name: build for PR

on:
  pull_request:
    paths:
      - "setup_ubuntu20.04.sh"
      - "ansible/**"
  workflow_dispatch:

jobs:
  build-pr:
    runs-on: ubuntu-20.04

    steps:
      # https://github.community/t/bug-strange-no-space-left-on-device-ioexceptions-on-github-runners/17616
      - name: Free disk space
        run: |
          sudo apt-get -y --allow-remove-essential purge \
            aria2 ansible azure-cli shellcheck rpm xorriso zsync clang* dotnet-sdk* esl-erlang firefox g++-8 gfortran* \
            google* ghc* cabal-install* imagemagick libmagick* ant ant-optional kubectl libnginx* \
            mercurial apt-transport-https mono-complete mysql-client libmysqlclient-dev mysql-server mssql-tools unixodbc-dev \
            yarn chrpath libssl-dev libxft-dev libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev php*
          sudo apt-get -y autoremove
          sudo apt-get -y autoclean
          sudo rm -rf /usr/local/lib/android
          docker rmi $(docker image ls -aq)
          df -h

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pip
        run: |
          sudo apt-get -y update
          sudo apt-get -y install python3-pip

      - name: Install tools
        run: |
          sudo apt-get -y update
          sudo apt-get -y install curl git

      - name: Fix autoware.proj.repos for private repositories
        run: |
          sed -i -e "s|git@github.com:|https://github.com/|g" autoware.proj.repos

      - name: Set git config for private repositories
        run: |
          git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global url.https://${{ secrets.REPO_TOKEN }}@github.com.insteadOf 'https://github.com'

      - name: Install vcstool
        run: |
          sudo apt update && sudo apt install curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt-get update && sudo apt-get install python3-vcstool

      - name: Run vcs import
        run: |
          mkdir src
          vcs import src < autoware.proj.repos

      - name: Run setup script
        run: |
          touch ~/.bashrc
          ./setup_ubuntu20.04.sh -c

      - name: Build
        run: |
          . /opt/ros/galactic/setup.sh
          colcon build \
            --event-handlers console_cohesion+ \
            --cmake-args -DCMAKE_BUILD_TYPE=Release
