name: update-ansible-galaxy-requirements

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update-ansible-galaxy-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up sd
        uses: kenji-miyake/setup-sd@v1

      - name: Get latest Autoware version
        id: get-latest-autoware-version
        run: |
          latest_hash=$(git ls-remote --heads https://github.com/autowarefoundation/autoware.git refs/heads/main | awk '{print $1}')
          echo ::set-output name=version::"$latest_hash"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Autoware version
        id: update-autoware-version
        run: |
          current_hash=$(yq '.collections[] | select(.name == "https://github.com/autowarefoundation/autoware.git#/ansible").version' ansible-galaxy-requirements.yaml)
          echo ::set-output name=current-version::"$current_hash"

          sd -f ms \
            '(https://github.com/autowarefoundation/autoware.git#/ansible.*version): \w+' \
            '$1: ${{ steps.get-latest-autoware-version.outputs.version }}' \
            ansible-galaxy-requirements.yaml

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          base: ${{ github.event.repository.default_branch }}
          branch: update-ansible-galaxy-requirements
          title: "chore: update ansible-galaxy-requirements.yaml"
          commit-message: "chore: update ansible-galaxy-requirements.yaml"
          body: |
            https://github.com/autowarefoundation/autoware/commits/main
            https://github.com/autowarefoundation/autoware/compare/${{ steps.update-autoware-version.outputs.current-version }}..${{ steps.get-latest-autoware-version.outputs.version }}
          labels: |
            bot
            dependencies
          signoff: true
          delete-branch: true

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
        shell: bash

      - name: Enable auto-merge
        if: ${{ steps.create-pr.outputs.pull-request-operation == 'created' }}
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: squash
