name: vcs import

on:
  pull_request:
    paths:
      - "autoware.proj.repos"
  workflow_dispatch:

jobs:
  vcs-import:
    runs-on: ubuntu-latest
    container: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-ros-base-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pip and apt-transport-https
        run: |
          apt-get -y update
          apt-get -y install python3-pip apt-transport-https

      - name: Add Autonomoustuff repository
        run: |
          sh -c 'echo "yaml https://s3.amazonaws.com/autonomoustuff-repo/autonomoustuff-public-galactic.yaml" > /etc/ros/rosdep/sources.list.d/40-autonomoustuff-public-galactic.list'
          sh -c 'echo "deb [trusted=yes] https://s3.amazonaws.com/autonomoustuff-repo/ focal main" > /etc/apt/sources.list.d/autonomoustuff-public.list'

      - name: Install tools
        run: |
          apt-get -y update
          apt-get -y install curl git

      - name: Fix autoware.proj.repos for private repositories
        run: |
          sed -i -e "s|git@github.com:|https://github.com/|g" autoware.proj.repos

      - name: Set git config for private repositories
        run: |
          git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global url.https://${{ secrets.REPO_TOKEN }}@github.com.insteadOf 'https://github.com'

      - name: Run vcs import
        run: |
          mkdir src
          vcs import src < autoware.proj.repos

      - name: Run rosdep install
        run: |
          apt-get -y update
          rosdep update
          DEBIAN_FRONTEND=noninteractive rosdep install -y --from-paths . --ignore-src --rosdistro galactic
